import type { Metadata } from 'next'
import { Assistant } from 'next/font/google'
import '@/styles/globals.scss'
import { getCrntUser } from '@/auth/authFuncs'
import Nav from '@/ui/Nav'
import GlobalPopMsg from '@/ui/GlobalPopMsg'

const font = Assistant({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Allin Crm',
  description: 'Generated by create next app',
  category: 'Personal',
  keywords: 'next.js, typescript, tailwind, react',
  icons: {
    icon: 'https://res.cloudinary.com/dfletli2x/image/upload/icons/reg/house-chimney-crack.svg',
    shortcut: 'https://res.cloudinary.com/dfletli2x/image/upload/icons/reg/house-chimney-crack.svg',
    apple: 'https://res.cloudinary.com/dfletli2x/image/upload/icons/reg/house-chimney-crack.svg',
  },
}

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const user = await getCrntUser()
  console.log('user', user)

  return (
    <html lang="he" dir="rtl">
      <body className={font.className}>
        <main className="app-container">
          <GlobalPopMsg />
          {user && (
            <>
              <Nav />
              <div />
            </>
          )}
          {children}
        </main>
      </body>
    </html>
  )
}
