import type { Metadata } from 'next'
import { Assistant } from 'next/font/google'
import '@/styles/globals.scss'
import 'jude_ui/style.css'
import { getUser } from '@/auth/authFuncs'
import Nav from '@/ui/Nav'
import PopMsg from 'jude_ui/pop'
import UserProvider from '@/utils/userCtx'

const font = Assistant({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Allin Crm',
  description: 'Generated by create next app',
  category: 'Personal',
  keywords: 'next.js, typescript, tailwind, react',
  icons: {
    icon: 'https://res.cloudinary.com/dfletli2x/image/upload/icons/reg/house-chimney-crack.svg',
    shortcut: 'https://res.cloudinary.com/dfletli2x/image/upload/icons/reg/house-chimney-crack.svg',
    apple: 'https://res.cloudinary.com/dfletli2x/image/upload/icons/reg/house-chimney-crack.svg',
  },
}

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const user = await getUser()

  return (
    <html lang="he" dir="rtl">
      <body className={font.className}>
        <UserProvider data={user}>
          <div className="app-container">
            <PopMsg />
            {user && (
              <>
                <Nav />
                <div />
              </>
            )}
            <main className="overflow-x-hidden wrap">{children}</main>
          </div>
        </UserProvider>
      </body>
    </html>
  )
}
