import type { Metadata } from 'next'
import { Assistant } from 'next/font/google'
import '@/styles/globals.scss'
import ToastComp from '@/components/Toast'

const font = Assistant({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Allin Crm',
  description: 'Generated by create next app',
  category: 'Personal',
  keywords: 'next.js, typescript, tailwind, react',
  icons: {
    icon: 'https://res.cloudinary.com/dfletli2x/image/upload/icons/reg/house-chimney-crack.svg',
    shortcut: 'https://res.cloudinary.com/dfletli2x/image/upload/icons/reg/house-chimney-crack.svg',
    apple: 'https://res.cloudinary.com/dfletli2x/image/upload/icons/reg/house-chimney-crack.svg',
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="he" dir="rtl">
      <body className={font.className}>
        <ToastComp />
        {children}
      </body>
    </html>
  )
}
